import type { InsightRule } from '../types';

export const INSIGHT_RULES: InsightRule[] = [
  {
    insight_code: 'self_definition_expands_through_visibility',
    category: 'theme',
    section: 'personality',
    priority_base: 8,
    activation_mode: 'any_of',
    required_tags: ['self.values.self_definition', 'self.temperament.magnetic_visibility'],
    optional_tags: ['spirit.archetypes.sovereign_presence', 'career.leadership_style.public_leadership'],
    negative_tags: ['self.shadow.control_through_withdrawal'],
    min_score: 0.6,
    render_hints: { tone: 'encouraging', avoid_absolutes: true, suggested_section: 'personality' },
  },
  {
    insight_code: 'interiority_needs_trust_and_processing_space',
    category: 'theme',
    section: 'personality',
    priority_base: 8,
    activation_mode: 'all_of_any_group',
    required_groups: [
      ['self.temperament.deep_internalization', 'relationship.attachment_style.slow_to_trust'],
      ['self.temperament.deep_internalization', 'self.shadow.control_through_withdrawal'],
    ],
    optional_tags: ['relationship.family_patterns.early_responsibility'],
    negative_tags: [],
    min_score: 0.62,
    render_hints: { tone: 'reflective', avoid_absolutes: true, suggested_section: 'personality' },
  },
  {
    insight_code: 'thinking_prefers_pattern_and_strategy',
    category: 'strength',
    section: 'personality',
    priority_base: 7,
    activation_mode: 'any_of',
    required_tags: ['self.decision_style.analytic_patterning', 'self.decision_style.strategic_indirection'],
    optional_tags: ['self.decision_style.dual_track_thinking', 'spirit.symbolic_themes.inner_refinement'],
    negative_tags: ['self.temperament.fast_reactivity'],
    min_score: 0.58,
    render_hints: { tone: 'clinical', avoid_absolutes: true, suggested_section: 'personality' },
  },
  {
    insight_code: 'bonds_need_reassurance_but_open_slowly',
    category: 'theme',
    section: 'relationships',
    priority_base: 9,
    activation_mode: 'all_of_any_group',
    required_groups: [
      ['relationship.attachment_style.reassurance_hunger', 'relationship.attachment_style.slow_to_trust'],
      ['relationship.attachment_style.reassurance_hunger', 'relationship.attachment_style.high_selectivity'],
    ],
    optional_tags: ['relationship.family_patterns.early_responsibility'],
    negative_tags: [],
    min_score: 0.64,
    render_hints: { tone: 'warm', avoid_absolutes: true, suggested_section: 'relationships' },
  },
  {
    insight_code: 'partnerships_can_be_intense_and_formative',
    category: 'theme',
    section: 'relationships',
    priority_base: 8,
    activation_mode: 'any_of',
    required_tags: ['relationship.partnership_dynamics.intense_bonding'],
    optional_tags: ['self.shadow.control_through_withdrawal', 'relationship.attachment_style.slow_to_trust'],
    negative_tags: ['relationship.social_mode.networked_support'],
    min_score: 0.6,
    render_hints: { tone: 'reflective', avoid_absolutes: true, suggested_section: 'relationships' },
  },
  {
    insight_code: 'career_compounds_through_discipline',
    category: 'strength',
    section: 'career',
    priority_base: 9,
    activation_mode: 'all_of_any_group',
    required_groups: [
      ['career.strengths.earned_respect', 'career.strengths.specialist_mastery'],
      ['career.trajectory.late_bloomer', 'wealth.earning_style.accumulative_discipline'],
    ],
    optional_tags: ['purpose.lessons.delayed_maturation'],
    negative_tags: [],
    min_score: 0.64,
    render_hints: { tone: 'clinical', avoid_absolutes: true, suggested_section: 'career' },
  },
  {
    insight_code: 'leadership_grows_with_public_exposure',
    category: 'opportunity',
    section: 'career',
    priority_base: 8,
    activation_mode: 'any_of',
    required_tags: ['career.leadership_style.public_leadership', 'self.temperament.magnetic_visibility'],
    optional_tags: ['timing.upcoming_cycle.visibility_rise', 'spirit.archetypes.sovereign_presence'],
    negative_tags: ['self.shadow.overresponsibility'],
    min_score: 0.6,
    render_hints: { tone: 'encouraging', avoid_absolutes: true, suggested_section: 'career' },
  },
  {
    insight_code: 'money_builds_best_with_patience_and_structure',
    category: 'theme',
    section: 'money',
    priority_base: 7,
    activation_mode: 'single_tag',
    required_tags: ['wealth.earning_style.accumulative_discipline'],
    optional_tags: ['career.strengths.specialist_mastery', 'purpose.lessons.delayed_maturation'],
    negative_tags: ['wealth.earning_style.volatile_growth'],
    min_score: 0.57,
    render_hints: { tone: 'clinical', avoid_absolutes: true, suggested_section: 'money' },
  },
  {
    insight_code: 'money_needs_clear_risk_edges',
    category: 'risk',
    section: 'money',
    priority_base: 7,
    activation_mode: 'single_tag',
    required_tags: ['wealth.earning_style.volatile_growth'],
    optional_tags: ['self.temperament.fast_reactivity'],
    negative_tags: ['wealth.earning_style.accumulative_discipline'],
    min_score: 0.57,
    render_hints: { tone: 'clinical', avoid_absolutes: true, suggested_section: 'money' },
  },
  {
    insight_code: 'current_cycle_favors_structured_visibility',
    category: 'opportunity',
    section: 'timing',
    priority_base: 8,
    activation_mode: 'all_of_any_group',
    required_groups: [
      ['timing.upcoming_cycle.visibility_rise', 'career.leadership_style.public_leadership'],
      ['timing.upcoming_cycle.visibility_rise', 'self.temperament.magnetic_visibility'],
    ],
    optional_tags: [],
    negative_tags: ['timing.current_season.consolidation_phase'],
    min_score: 0.61,
    render_hints: { tone: 'encouraging', avoid_absolutes: true, suggested_section: 'timing' },
  },
  {
    insight_code: 'this_phase_requires_consolidation',
    category: 'theme',
    section: 'timing',
    priority_base: 8,
    activation_mode: 'single_tag',
    required_tags: ['timing.current_season.consolidation_phase'],
    optional_tags: ['career.strengths.earned_respect', 'purpose.lessons.delayed_maturation'],
    negative_tags: ['timing.upcoming_cycle.visibility_rise'],
    min_score: 0.6,
    render_hints: { tone: 'reflective', avoid_absolutes: true, suggested_section: 'timing' },
  },
  {
    insight_code: 'growth_runs_through_delayed_maturation',
    category: 'growth',
    section: 'growth',
    priority_base: 8,
    activation_mode: 'any_of',
    required_tags: ['purpose.lessons.delayed_maturation', 'career.trajectory.late_bloomer'],
    optional_tags: ['self.shadow.overresponsibility'],
    negative_tags: [],
    min_score: 0.6,
    render_hints: { tone: 'reflective', avoid_absolutes: true, suggested_section: 'growth' },
  },
  {
    insight_code: 'inner_crises_reorganize_identity',
    category: 'growth',
    section: 'growth',
    priority_base: 7,
    activation_mode: 'all_of_any_group',
    required_groups: [
      ['purpose.lessons.crisis_repatterning', 'self.growth_pattern.self_reinvention'],
      ['purpose.lessons.crisis_repatterning', 'self.shadow.control_through_withdrawal'],
    ],
    optional_tags: [],
    negative_tags: [],
    min_score: 0.6,
    render_hints: { tone: 'reflective', avoid_absolutes: true, suggested_section: 'growth' },
  },
  {
    insight_code: 'energy_management_needs_attention',
    category: 'risk',
    section: 'shadow',
    priority_base: 7,
    activation_mode: 'single_tag',
    required_tags: ['health.vitality.fluctuating_reserves'],
    optional_tags: ['self.shadow.overresponsibility'],
    negative_tags: [],
    min_score: 0.56,
    render_hints: { tone: 'warm', avoid_absolutes: true, suggested_section: 'shadow' },
  },
];
